import type { Metadata } from "next";
import { BBH_Sans_Bartle, DM_Sans } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import { getServerSession } from "@/utils/auth";
import { AuthProvider } from "@/components/auth/authProvider";

const dmSans = DM_Sans({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  style: ['normal', 'italic'],
  variable: '--font-dm-sans',
  display: 'swap',
});

const bbhBartle = BBH_Sans_Bartle({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-bbh-bartle',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Cosmik - Movie Catalog App",
  description: "Generated by Cosmik",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en" className={`${dmSans.variable} ${bbhBartle.variable}`}>
      <body
        className={`font-dm-sans antialiased bg-slate-900 text-white`}
      >
        <AuthProvider>
          {children}
        <Toaster position="top-center" richColors closeButton />
        </AuthProvider>
      </body>
    </html>
  );
}
